### PR TITLE
WIP Update index.rst

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
more small fixes ...

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Argh @dengemann it was WIP :)

**Comment by dengemann** [comment]
> Argh @dengemann it was WIP :)

just push to master.

**Comment by jona-sassenhagen** [comment]
Do I actually have access?.. It seems not from the web interface.

**Comment by dengemann** [comment]
You should have now.

**Comment by jona-sassenhagen** [comment]
So far, so good. I'll try to do something actually important and useful later on :D

**Comment by dengemann** [comment]
Thanks @jona-sassenhagen

**Pull request merged**
