### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Just a bit of language.

### CODE REVIEW

**Comment by dengemann** [comment]
In general checkout the website; we may want to improve the firs impression. Maybe show the simple hcp code at the first glance: it's so easy to access the data; etc.

**Comment by jona-sassenhagen** [comment]
That was fast :) I may do another one like these soon, that was just at first glance.

**Comment by dengemann** [comment]
>  I may do another one like these soon, that was just at first glance.

did you have a chance to install the dev setup?
we need a doc for that btw.

checkout the downloader in hcp.tests;
with this you can build the website in doc.
For index.rst feel free to push to master. 
We can slow down later.

**Comment by jona-sassenhagen** [comment]
Ok ... I have a lot of catching up to do.

**Comment by dengemann** [comment]
Yeah ... I'd recommend you to to look at the tests in io. They are
revealing.  Then take a look at the travis.yml to see how travis does it.

**Pull request merged**
