### PR TITLE
FIX: Add tests for preproc

### PR DESCRIPTION
**Pull request by dengemann**
Taking over #39 to trigger correct Travis build. @Eric89GXL

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I [changed Travis] (https://travis-ci.org/mne-tools/mne-hcp/settings) not to build PRs anymore, just pushes

**Comment by dengemann** [comment]
> I changed Travis not to build PRs anymore, just pushes

Well for PRs from the original repo builds would still be good.

**Comment by Eric89GXL** [comment]
Don't need to, those count as pushes (e.g., this PR has two identical travis builds going right now, one push, one PR)

**Comment by dengemann** [comment]
> Don't need to, those count as pushes

Ahh. Right. And they are failing now for other reasons.

**Comment by Eric89GXL** [comment]
... and I just pushed a fix and it appears to work fine

**Comment by Eric89GXL** [comment]
Do you have codecov status printing turned off?

**Comment by Eric89GXL** [comment]
Pushed a codecov tweak

**Comment by Eric89GXL** [comment]
In any case, this gets us up to [69%] (https://codecov.io/gh/mne-tools/mne-hcp/branch/tweaks)

**Comment by dengemann** [comment]
Thanks @Eric89GXL !

**Pull request merged**
